[project]
name = "convert-text"
version = "0.0.9"
description = "Python script to convert .txt to .html or .pdf."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fpdf>=1.7.2",
]
